### ISSUE TITLE
version-chooser: UI broken for long image names

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#1027]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/6551040/171508112-b3c2c36b-5ee3-4745-8e8b-4566ff899a36.png">

Maybe for those cases, we should reduce font size and allow two-line wrapping.

**Comment by patrickelectric** [comment]
maybe we can add the thing that moves the text from right to left as an animation ?

**Comment by rafaellehmkuhl** [comment]
Definitely cool
