### ISSUE TITLE
core: camera-manager: restore last settings on startup

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS#1030]
### Current behaviour

Currently any cameras BlueOS encounters on startup are auto-configured, which is then stored persistently. If a user wants to change the configuration to something else (e.g. not stream a camera, or change its resolution, etc) then they currently need to change that every time they use their device, because manual configuration is not persistent.

Idea was raised in [this forum post](https://discuss.bluerobotics.com/t/disable-automatic-video-display-on-qgroundcontrol/12109/4), where it was causing issues for someone's setup.

### Expected or desired behaviour

Ideally the last settings that were applied should be the ones that attempt to start on next boot. Practically speaking that means "if the user changes the configuration manually, save that new configuration persistently".

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
Unable to replicate:
![Peek 03-06-2022 08-30](https://user-images.githubusercontent.com/1215497/171845751-664ca294-00fd-4247-b986-8d5bf6ec1d29.gif)
