### ISSUE TITLE
Timeout error, but still connects (to wifi)

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#1146]
When trying to connect to a wifi network, I'm getting a 20 seconds timeout error, but it still connects:

https://user-images.githubusercontent.com/5920286/189787898-8bc2a5c1-4499-44d3-991b-18af2cbc18b0.mp4

**Comment by rafaellehmkuhl** [comment]
Will check! Thanks!

**Comment by dgudiel** [comment]
Also have this problem on a fresh install of beta21

**Comment by joaoantoniocardoso** [comment]
Closed by https://github.com/bluerobotics/BlueOS/pull/1904
