### ISSUE TITLE
bug: ardupilot-manager: restarting Pixhawk fails to reconnect

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS#1155]
### Bug description

When using a Pixhawk, it works to restart from the General page (and it seemingly does restart properly, I see the status LEDs turn off and then it goes through its normal boot sequence), but then BlueOS fails to reconnect to it until fully rebooted.

When I tell the autopilot to restart: 
[logfile_09-20-2022_00_48_11.log](https://github.com/bluerobotics/BlueOS-docker/files/9603190/logfile_09-20-2022_00_48_11.log)

After I restart the core container:
[logfile_09-20-2022_00_54_33.log](https://github.com/bluerobotics/BlueOS-docker/files/9603193/logfile_09-20-2022_00_54_33.log)

Connects correctly after a reboot:
[logfile_09-20-2022_00_58_58.log](https://github.com/bluerobotics/BlueOS-docker/files/9603199/logfile_09-20-2022_00_58_58.log)

---

The individual "Stop Autopilot" and "Start Autopilot" commands available in Pirate Mode do seem to work, albeit in a bit of a roundabout way because they don't actually restart the Pixhawk, just stop and start the connection to it (or maybe just the telemetry forwarding? not sure). Regardless, the issue here is specifically with the Restart Autopilot button, which does actually try to restart the autopilot itself.

### Steps to reproduce

1. Connect a Pixhawk to BlueOS
2. Go to the General page of the web interface
3. Press the "Restart Autopilot" button
4. Note that BlueOS fails to re-detect the autopilot, and is not forwarding MAVLink to the topside
6. Try to restart BlueOS's core container
7. Note that the autopilot is still not being detected
8. Reboot BlueOS
9. Autopilot is detected again

### Primary pain point(s)

It's annoying to have a convenience feature that appears to be available but then actually isn't - it ends up wasting time instead of saving it.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by ES-Alexander** [comment]
Difference in `lsusb` after the autopilot is restarted
```
< Bus 001 Device 007: ID 1209:5741 Generic Pixhawk1
---
> Bus 001 Device 009: ID 1209:5741 Generic Pixhawk1
```

Difference in `dmesg` after the autopilot is restarted
```
> [  790.034127] usb 1-1.3: USB disconnect, device number 7
> [  790.331782] usb 1-1.3: new full-speed USB device number 8 using dwc_otg
> [  790.464007] usb 1-1.3: language id specifier not provided by device, defaulting to English
> [  790.465251] usb 1-1.3: New USB device found, idVendor=26ac, idProduct=0011, bcdDevice= 1.01
> [  790.465267] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [  790.465278] usb 1-1.3: Product: PX4 BL FMU v2.x
> [  790.465288] usb 1-1.3: Manufacturer: 3D Robotics
> [  790.465298] usb 1-1.3: SerialNumber: 0
> [  795.155062] usb 1-1.3: USB disconnect, device number 8
> [  795.451711] usb 1-1.3: new full-speed USB device number 9 using dwc_otg
> [  795.593942] usb 1-1.3: New USB device found, idVendor=1209, idProduct=5741, bcdDevice= 2.00
> [  795.593962] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [  795.593982] usb 1-1.3: Product: Pixhawk1
> [  795.593989] usb 1-1.3: Manufacturer: ArduPilot
> [  795.593997] usb 1-1.3: SerialNumber: 160038001151393435393230
```

**Comment by patrickelectric** [comment]
@ES-Alexander is this still a thing ?

**Comment by ES-Alexander** [comment]
Just checked on latest beta and I can't replicate it.

Not sure when it got fixed (probably a while ago), but regardless, it does seem to be fixed now :-)
