### ISSUE TITLE
We should allow users to use USB ports for Ardupilot.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#1158]
They are currently hard-coded here:
https://github.com/bluerobotics/BlueOS-docker/blob/master/core/services/ardupilot_manager/ArduPilotManager.py#L121-L147

It would be nice to allow users to change some of those for usb devices, for example.
We could maybe use of symlinks for that.

**Comment by rafaellehmkuhl** [comment]
Yup.
That would be for serial devices that don't talk Mavlink, right? For the Mavlink ones it's currently possible to create a bridge and a mavlink endpoint.

**Comment by Williangalvani** [comment]
> That would be for serial devices that don't talk Mavlink, right? 

Yep, mavlink or other protocols supported by Ardupilot itself.

**Comment by patrickelectric** [comment]
That's now possible
