### ISSUE TITLE
bug: bridge stop working at every power cycle

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#1163]
A user (throug Daniel) reported that everytime he power cycle his ROV, the bridge link stops working. It continues to be there in BlueOS, but to make it work, he has to redo it.

User reported being in BlueOS 1.1.0 beta9.

Attached are two logfiles from the user.

[logfile_10-07-2022_09_39_47 set up bridge.log](https://github.com/bluerobotics/BlueOS-docker/files/9759436/logfile_10-07-2022_09_39_47.set.up.bridge.log)
[logfile_10-07-2022_09_49_28 after restart.log](https://github.com/bluerobotics/BlueOS-docker/files/9759438/logfile_10-07-2022_09_49_28.after.restart.log)

**Comment by rafaellehmkuhl** [comment]
@patrickelectric we discussed this problem some time ago, right?

**Comment by patrickelectric** [comment]
I believe that is not an issue anymore
