### ISSUE TITLE
Allow uploading dockers via the browser

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#1278]
This will help a lot with convenience. I was helping a user debug and they had a lot of trouble getting the rov out of the water and connected to internet.

**Comment by patrickelectric** [comment]
That's more important for extensions, since the only way possible to update it is with internet

**Comment by patrickelectric** [comment]
This is possible for BlueOS but not for extensions, replaced by: https://github.com/bluerobotics/BlueOS/issues/1614
