### ISSUE TITLE
map ttyAMA ports to Ardupilot SERIALX

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#1289]

**Comment by Williangalvani** [comment]
https://github.com/bluerobotics/BlueOS-docker/blob/master/core/services/ardupilot_manager/ArduPilotManager.py#L122-L125

**Comment by Williangalvani** [comment]
I mean in the blueOS ui, when using a navigator board

**Comment by patrickelectric** [comment]
Already available.
