### ISSUE TITLE
Installed extension icon on side menu disappeared

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#1549]
I've installed CeruleanDocs extension, the icon in the side-menu appeared, I started browsing the docs and eventually the icon disappeared.

<img width="1008" alt="image" src="https://user-images.githubusercontent.com/6551040/226464511-3a939136-5372-4de8-89d1-66d29b35a797.png">

**Comment by patrickelectric** [comment]
This is not a problem anymore and the submental are not being used at the moment.
