### ISSUE TITLE
core: frontend: extensions manager not showing some manually installed extensions

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS#1668]
### Current behaviour

When manually installing extensions (via the + button), it seems like they don't always show up in the Installed page.

Brought up in discussion with @wlseb, who installed
```
waterlinked.ugps
WaterLinked UGPS
waterlinked/blueos-ugps-extension
latest
{
  "NetworkMode": "host",
  "Env": [
	"UGPS_HOST=http://192.168.2.94/",
	"MAVLINK_HOST=http://192.168.2.2:6040/",
	"QGC_IP=192.168.2.1",
    "EXTRA_ARGS=--ignore_gps --ignore_acoustic"
  ]
}
```

which successfully pulled the image and ran the container (which I confirmed with `docker ps -a` and `docker container ls`, as well as `docker attach` and `docker logs` to ensure it was running as expected), but it did not show up in the manager.

I then tried manually installing `v1.0.4` instead of `latest`, which worked and _did_ show up in the manager. I'm thinking maybe the Installed page is still filtering by SemVer or something, even though it shouldn't be.

### Expected or desired behaviour

All installed extensions should show up in the Installed page of the manager, regardless of their version name or whether they're successfully working.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by Williangalvani** [comment]
this should have been fixed by https://github.com/bluerobotics/BlueOS/pull/2137
