### ISSUE TITLE
[reset settings] Reset settings sets image back to factory without notice

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#1730]
It is not clear to me whether reset settings should change the image back to the factory. If so, we need at least notify the user about it and let him decide beforehand.

Example:

https://github.com/bluerobotics/BlueOS-docker/assets/5920286/ad98df05-c1b3-4419-83c6-e1f94290637e

**Comment by joaoantoniocardoso** [comment]
Relates to #1719

**Comment by Williangalvani** [comment]
perhaps we shoul rename it to "factory reset" ? if that is the intended behavior

**Comment by joaoantoniocardoso** [comment]
> perhaps we shoul rename it to "factory reset" ? if that is the intended behavior

I think this works

**Comment by patrickelectric** [comment]
WOW, that should not happen at all, we should have a button just for factory reset.
