### ISSUE TITLE
we should show if there is a gps signal positioning

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#1749]

**Comment by ES-Alexander** [comment]
Isn't that more relevant within a control station software?

Or are you thinking within the Vehicle Setup page, as part of the status of a position-enabled sensor or something?

**Comment by Williangalvani** [comment]
> Isn't that more relevant within a control station software?
> 
> Or are you thinking within the Vehicle Setup page, as part of the status of a position-enabled sensor or something?

it is _more_ relevant for a gcs, but I think it is also worth displaying here.

I'm thinking a gps icon at the top bar if it is detected, and nothing if it is not detected (so users without gps don't feel there is something wrong)
