### ISSUE TITLE
Current scrollbars are ugly...

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#1793]
We should improve their look. They are currently very dissonant from the rest of the project.

![image](https://github.com/bluerobotics/BlueOS-docker/assets/6551040/380ee208-6ada-469a-b3c6-0d4fd2139e69)

**Comment by joaoantoniocardoso** [comment]
To add to the discussion, on Firefox the default is a fancy thin bar that fades itself:

https://github.com/bluerobotics/BlueOS-docker/assets/5920286/c32e23e5-250a-46b7-8466-91bd59bfc5ab

**Comment by rafaellehmkuhl** [comment]
> 

Much better. We should re-style to something like that.

**Comment by patrickelectric** [comment]
The scrollbars are now pretty.
