### ISSUE TITLE
Scrollbars are appearing without need on i-frame services

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#1794]
Take a look at the File Browser or the Terminal pages:

![image](https://github.com/bluerobotics/BlueOS-docker/assets/6551040/380ee208-6ada-469a-b3c6-0d4fd2139e69)

**Comment by patrickelectric** [comment]
This appears to be a problem only in ttyd, from what I could find, it appears to be a problem of the project itself.
