### ISSUE TITLE
bug: wizard progress bar has no section for internet

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS#1830]
### Bug description

When going through the wizard the first stage is internet connection, but there's no stage for it in the progress bar at the top, which means all subsequent stages show as one ahead in the progress compared to their actual state.

For example, this is the "Choose Vehicle" stage, but it shows as the Customise stage:

<img width="541" alt="wizard-vehicle" src="https://github.com/bluerobotics/BlueOS-docker/assets/25898329/0abbae04-8309-4838-836e-34fac41b8c6e">

### Steps to reproduce

1. Run the wizard (e.g. on a fresh install of BlueOS, or by reducing the wizard version in Bag Editor and refreshing the page)
2. Check the progress bar at the top while going through the steps (they're all 1 ahead of where they're supposed to be)

### Primary pain point(s)

It's confusing to see it claiming to be in a different state to the actual one.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
I saw the same behavior

**Comment by joaoantoniocardoso** [comment]
There's the possibility of losing the internet after the internet step, so we probably should go back to that step if the connection fails.

**Comment by joaoantoniocardoso** [comment]
I believe this is fixed:

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/3cba6352-5ba1-40ee-b189-f117674af5b8)
