### ISSUE TITLE
[mavlink2rest] 404 Not Found on POST mavlink2rest/mavlink

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#1967]
Every time I open BlueOS, this happens:

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/684be785-4f18-43f7-8c1e-cc9652923440)
![image](https://github.com/bluerobotics/BlueOS/assets/5920286/709707af-c72b-4f1f-aa20-100d62f8122e)
![image](https://github.com/bluerobotics/BlueOS/assets/5920286/376cc27f-7ce4-4f96-9895-462a3338eba4)

**Comment by patrickelectric** [comment]
We did test and was unable to replicate ons @joaoantoniocardoso system
