### ISSUE TITLE
[autopilot parameters] Weird down step size

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#1995]
https://github.com/bluerobotics/BlueOS/assets/5920286/ddac45ce-2377-491a-bb4e-3776e0b0c021

**Comment by patrickelectric** [comment]
Unable to replicate on latest master

**Comment by patrickelectric** [comment]
@joaoantoniocardoso can we close this ?

**Comment by joaoantoniocardoso** [comment]
Yep, we can close it, this was potentially solved by #1997, it might had something to do with the validation somehow..?

https://github.com/bluerobotics/BlueOS/assets/5920286/29260633-010e-4a2f-9db5-cf09a8646b67
