### ISSUE TITLE
[kraken] failed to show version "master"

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#1998]
Able to install an extension tag "master", but Kraken doesn't show it:

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/3e5a0459-25c1-4d0e-9bef-6381ff6202e5)

**Comment by joaoantoniocardoso** [comment]
After restarting it is showing the `master`... :eyes:

**Comment by Williangalvani** [comment]
this should have been fixed by #2137 , can you check?

**Comment by joaoantoniocardoso** [comment]
@Williangalvani thanks, closed by https://github.com/bluerobotics/BlueOS/pull/2137
