### ISSUE TITLE
bug: [Terminal] : User can't use terminal anymore if execute "exit"

### ISSUE THREAD

**Issue by RaulTrombin** [bluerobotics/BlueOS#2035]
### Bug description

User cannot regain control in the terminal if misuse the exit command.

### Steps to reproduce

![CPT2308241522-1166x980](https://github.com/bluerobotics/BlueOS/assets/80598030/effdba47-78fc-4239-839c-7016744745de)

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by joaoantoniocardoso** [comment]
yeah, we should create an alias:
```bash
alias exit='clear'
```
