### ISSUE TITLE
bug: file browser: after "Download files" popup closes, the main browser pane is still unselectable

### ISSUE THREAD

**Issue by clydemcqueen** [bluerobotics/BlueOS#2048]
### Bug description

If I select 2 files and download them, I get a popup asking me to choose a format (zip, etc.) This popup grays out the pane behind it, as expected.

After the popup disappears, the pane is still grayed out / unselectable.

![image](https://github.com/bluerobotics/BlueOS/assets/4961326/bafd54fe-47a6-4674-ba1d-f33c106b81cd)

BlueOS Version: [tags/1.1.0-beta.28-0-g2df6ae03](https://github.com/bluerobotics/blueos-docker/releases/tag/1.1.0-beta.28)
Bootstrap Version: 1.0.1
Build: 8/12/2023, 8:51:38 PM
By [Blue Robotics](https://bluerobotics.com/)

Filebrowser 2.15.0

Client:
Ubuntu 22.04
Version 116.0.5845.110 (Official Build) (64-bit)

### Steps to reproduce

1. select "File browser"
2. select 2 or more files or folders
3. select a format in the popup, e.g., "zip"
4. the file browser pane is grayed out / unselectable

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by joaoantoniocardoso** [comment]
I can reproduce it on Chrome-based browsers. It seems to not be a problem on Firefox, so you can try it as a workaround until we fix it.
