### ISSUE TITLE
BlueOS version reverted to factory setting

### ISSUE THREAD

**Issue by zhrandell** [bluerobotics/BlueOS#2105]
When opening BlueOS today there was a notification that the version running on our BlueROV was reverted to the factory setting. We are posting this issue along with the attached zip file of the system logs as suggested in the notification. 

[system_logs.zip](https://github.com/bluerobotics/BlueOS/files/12611611/system_logs.zip)

**Comment by joaoantoniocardoso** [comment]
Closed by #2265
