### ISSUE TITLE
Ardusub stops responding until mavlink-router is killed

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#2115]
This happened to me running ArduSub master today. I checked htop and it seemed fine, so I killed mavlink-router and communication was restored.

Blueos was on a branch rebased earlier today.
[logfile_09-18-2023_21_03_40.2023-09-18_22-14-32_956785.log](https://github.com/bluerobotics/BlueOS/files/12653923/logfile_09-18-2023_21_03_40.2023-09-18_22-14-32_956785.log)

**Comment by patrickelectric** [comment]
@Williangalvani is this still an issue ?

**Comment by Williangalvani** [comment]
hasnt happened in a long time. I cant even remember it, so I'll close it.
