### ISSUE TITLE
WiFi tray icon is showing `NetworkCard` from the System Info page

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#2133]
![image](https://github.com/bluerobotics/BlueOS/assets/6551040/44150310-e1cd-4fe2-ba64-f0dd41c3f62e)

**Comment by Williangalvani** [comment]
relevant (sporadic) error message:

```
[unplugin-vue-components] component "NetworkCard"(/home/will/git/blueos/blueos-docker/core/frontend/src/components/wifi/NetworkCard.vue) has naming conflicts with other components, ignored.
```

**Comment by patrickelectric** [comment]
@rafaellehmkuhl can you inform how to replicate this issue ?
Master looks fine here

![image](https://github.com/bluerobotics/BlueOS/assets/1215497/7b72eb7d-6784-4391-8495-2c873d6cb87f)

**Comment by rafaellehmkuhl** [comment]
I dont know how to replicate the issue. I'm literally just opening the page.
Cache disabled.
Master image `718caeee`.

**Comment by rafaellehmkuhl** [comment]
Updating to the latest master (`0c568f94`) didnt solve the issue.

@patrickelectric your screenshot is from production or local development?
