### ISSUE TITLE
Helper service not showing on the list of available services

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#2143]

**Comment by joaoantoniocardoso** [comment]
## 1.1.0

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/8df617da-1aa6-4a49-a0cb-1ba4f75cda2c)

## 1.1.1

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/64c90d65-6916-4038-8a35-2ee13a9b1a2d)

## Master (0c568f94 - 2 days ago)

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/6b032f9c-1cbe-452e-a5c9-ba9015ba1dd9)
