### ISSUE TITLE
The connection indicator wrongly flags a zerotier connection as not cabled

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#2198]
![image](https://github.com/bluerobotics/BlueOS/assets/6551040/e2ef4496-2321-405c-8334-263df6efcbec)

This is appearing for a cabled ROV being accessed through Zerotier.

**Comment by Williangalvani** [comment]
maybe we should rephrase this so it says "you are not reaching BlueOS through a direct connection"? 🤔 

thoughts?

**Comment by patrickelectric** [comment]
"It looks like you don't have a directly connection with BlueOS. Degraded performance can happen when using it through wi-fi or a complex network."
