### ISSUE TITLE
Websockets don't work reliably on dev server since the migration to Vite

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#2207]

**Comment by joaoantoniocardoso** [comment]
example..?

**Comment by Williangalvani** [comment]
on both my machines:

mac m1 with node v18.12.1 and Arch linux with Node 20.3.1

`[yarn|bun] dev `  results in websocket taking more than 3 minutes to connect.
adding `--host` seems to fix the issue. I'll investigate further.

**Comment by Williangalvani** [comment]
Reopening. The issue is is reproducible if yarn is running on a different computer than the one you are browsing from.

**Comment by patrickelectric** [comment]
is this still an issue ? what are you experiencing with it ?

**Comment by Williangalvani** [comment]
yeah. it is happening right now. I am running `BLUEOS_ADDRESS=http://192.168.15.132 yarn dev --host` on a machine, and accessing the frontend from a different machine.
All websockets are pending (except one used by the dev server for hotreload):
<img width="817" alt="image" src="https://github.com/bluerobotics/BlueOS/assets/4013804/90a29c72-34d3-4841-ba0d-7d7ffa156823">

**Comment by patrickelectric** [comment]
did you try this ?
https://stackoverflow.com/questions/69481783/http-requests-stuck-in-pending-state-when-using-vite/69673499#69673499

**Comment by Williangalvani** [comment]
> did you try this ? https://stackoverflow.com/questions/69481783/http-requests-stuck-in-pending-state-when-using-vite/69673499#69673499

That did solve the issue. I'm very confused. why are there so many open files?

Well. I guess I'll close the issue, but maybe we should document this somewhere?

**Comment by Williangalvani** [comment]
Also documented here:
https://vitejs.dev/guide/troubleshooting.html#dev-server
