### ISSUE TITLE
When an extension is installed, *apparently* nothing happens

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#2209]
The backend is working to startup the extension, but there is no feedback in the frontend for the user.
Most extensions take around 30 seconds to load, so usually the user will just think the install process didn't work.
We could (and should) have a feedback in the frontend. An idea would be to already place the extension in the side menu as a placeholder with a loading state/blurred and make it clickable when the extension actually starts.

**Comment by joaoantoniocardoso** [comment]
Is this a duplicate of https://github.com/bluerobotics/BlueOS/issues/1398?

**Comment by rafaellehmkuhl** [comment]
It actually is!
And wow, january haha

**Comment by rafaellehmkuhl** [comment]
Closing as duplicate of #1398.
