### ISSUE TITLE
Kraken is kind of dying sometimes. Appears to be something related to accessing extension logs.

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#2210]
This happens when trying to access logs from an extension. I tried with Cockpit initially, but others gave the same.

![image](https://github.com/bluerobotics/BlueOS/assets/6551040/83230e27-dd9b-40b1-989b-ec56b2aa5e7e)

![image](https://github.com/bluerobotics/BlueOS/assets/6551040/64b09b86-bad5-4ffe-ab43-ff6e8cce8766)

**Comment by joaoantoniocardoso** [comment]
What version are you running? Is this related to https://github.com/bluerobotics/BlueOS/pull/2124 ?

**Comment by rafaellehmkuhl** [comment]
> What version are you running? Is this related to #2124 ?

I don't think so.

```
BlueOS Version: [heads/master-0-ge85c728a](https://github.com/bluerobotics/blueos-docker/tree/e85c728a)
Bootstrap Version: 1.1.1
Build: 11/28/2023, 5:54:06 PM
By [Blue Robotics](https://bluerobotics.com/)
```

**Comment by Williangalvani** [comment]
@rafaellehmkuhl can you try williangalvani/blueos-core:stream_logs ?

**Comment by rafaellehmkuhl** [comment]
> @rafaellehmkuhl can you try williangalvani/blueos-core:stream_logs ?

Tested. No luck.

**Comment by Williangalvani** [comment]
I can't replicate. what extensions do you have installed?

**Comment by rafaellehmkuhl** [comment]
Those 3:
<img width="1188" alt="image" src="https://github.com/bluerobotics/BlueOS/assets/6551040/a8840c9b-8c35-4d32-a476-da70d4c968bd">

Still happening on latest master.

Attaching the logs below:

[_kraken.zip](https://github.com/bluerobotics/BlueOS/files/13574221/_kraken.zip)

**Comment by Williangalvani** [comment]
after some debugging, it seems like the vscode extension docker is.... insanely huge.
[logfile_12-06-2023_02_38_16.log](https://github.com/bluerobotics/BlueOS/files/13575237/logfile_12-06-2023_02_38_16.log)

is it trying to use pretty much all the ports in the system? 65k udp and 65k tcp:
```
>>> 131001-122
130879
>>> _/2
65439.5
```

**Comment by Williangalvani** [comment]
@patrickelectric any ideas of what could be causing this? I couldn't find anything obvious on the dockerfile or anywhere else. Docker's documentation barely mentions "PrivatePort", too.

**Comment by patrickelectric** [comment]
The ports are exposed via a range argument: https://github.com/BlueOS-community/blueos-code-server/blob/master/Dockerfile#L48

**Comment by Williangalvani** [comment]
I wonder if there is a way to do this dynamically. or maybe we should just do net=host? 

the root of the issue here is that the json returned by Docker's API and resulting python object are huge due to the 130k port entries.

I only see two ways out, we either increase the memory usage limit for Kraken or change this extension

**Comment by patrickelectric** [comment]
Can't we just filter our the Ports property from the API if it goes over a range ? Like: 100 ports ?
I believe that using ports range will be pretty common.

**Comment by Williangalvani** [comment]
we would have to reimplement the aiodocker `containers.list()` function, which isn't ideal. plus we'd be getting the huge json in memotry anyway to get rid of the 130k entries.

Do you recall why you had to add this? I don't understand how it works, since the allocated port won't be the port that vscode expects it to be

**Comment by patrickelectric** [comment]
VSCode extension, as jupyter, aims to be a development platform. 
For that, it's necessary to have a range of ports that the user can use to access BlueOS services and at the same time user services.
To do that, I have created a range 100-MAX for the ports, that's not for vscode, but for the user code/software that is running on the docker.

**Comment by patrickelectric** [comment]
I believe that we never had this problem again, closing it until further information
