### ISSUE TITLE
Frontend interface for extensions appears to be broken after latest updates

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#2216]
![image](https://github.com/bluerobotics/BlueOS/assets/1215497/ca31e071-ec1c-4f88-91fe-8037f0a326a4)

Probably after #2213 and #2214

**Comment by Williangalvani** [comment]
can you check if this got fixed by #2215 ?

**Comment by Williangalvani** [comment]
fixed by #2215
