### ISSUE TITLE
Services should be automatically restarted when killed due to high memory usage, and the user should be notified that this happened

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#2218]

**Comment by Williangalvani** [comment]
I see we doing that long-term. but we need a short-term fix.
We could have a wrapper around the services that runs then in a while true loop, delaying 5s after they die, or something similar

**Comment by joaoantoniocardoso** [comment]
@Williangalvani 

edit: the spawned process from the terminal should not interrupt the terminal, so a while loop should indeed just work :)

**Comment by Williangalvani** [comment]
our issue is not even the OOM killer, we introduced python code into our services to limit their memory usage, some of them are handling worse than others

**Comment by joaoantoniocardoso** [comment]
> our issue is not even the OOM killer, we introduced python code into our services to limit their memory usage, some of them are handling worse than others

OOOh, I forgot about that. So the "MemoryError" from #2232 is that memory limitation, probably?

**Comment by Williangalvani** [comment]
> OOOh, I forgot about that. So the "MemoryError" from #2232 is that memory limitation, probably?

yes
