### ISSUE TITLE
BlueOS should log system information

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#2258]
At least CPU + Memory + Temperature + Disk (the ones in the system monitor) would help a lot on debugging already.

<img width="1060" alt="image" src="https://github.com/bluerobotics/BlueOS/assets/6551040/3f5b02ea-ea48-40b7-b6d2-68fbc66255e7">

It would be also nice if the log started with BlueOS information (BlueOS version, Bootstrap version, etc).

**Comment by rafaellehmkuhl** [comment]
@patrickelectric I think you did that one right?

**Comment by patrickelectric** [comment]
Yes, done in https://github.com/bluerobotics/BlueOS/pull/2446
