### ISSUE TITLE
Bad report of reaching BlueOS through a non-wired connection

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#2362]
![image](https://github.com/bluerobotics/BlueOS/assets/4013804/1d4e5ff7-d2b6-40b3-b824-102b22ab56b0)
![image](https://github.com/bluerobotics/BlueOS/assets/4013804/13726a74-ff7e-487c-9dd2-ce687e014c97)

**Comment by JoaoMario109** [comment]
Closing it per now due to not be able to replicate and that #2423 added new checks that would avoid this issue to happen
