### ISSUE TITLE
vehicle setup: lights configuration showing for rover vehicle

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#2369]
There is also another thing, the page end up showing for rover as well, should we remove it ?

_Originally posted by @patrickelectric in https://github.com/bluerobotics/BlueOS/issues/2368#issuecomment-1930747586_

**Comment by ES-Alexander** [comment]
I'm pretty sure rover doesn't have joystick-based lights control, but we could maybe replace it with controls for the NavLight (including perhaps some nice configuration options of the flashing pattern, for example)?

**Comment by Williangalvani** [comment]
yeah, I'm thinking where we should filter it. Maybe filter here?
https://github.com/bluerobotics/BlueOS/blob/master/core/frontend/src/components/vehiclesetup/Configure.vue#L54
