### ISSUE TITLE
Calibration: Improve UI 3

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#2383]
This is visually annoying:

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/314bd5d8-4172-4af1-92a2-e580a948410b)

(could we just remove those gears?)

_Originally posted by @joaoantoniocardoso in https://github.com/bluerobotics/BlueOS/issues/2342#issuecomment-1924681875_

**Comment by Williangalvani** [comment]
those are gone already.
![image](https://github.com/bluerobotics/BlueOS/assets/4013804/d4137a66-9e15-4abf-bead-493079ca756d)
