### ISSUE TITLE
Mavlink Camera Manager is hitting the memory limit

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#2387]
![image](https://github.com/bluerobotics/BlueOS/assets/5920286/35b6eec5-fe81-436d-b4c8-b682d6c06821)

**Comment by Williangalvani** [comment]
what cameras? how many streams? that is a lot of memory...

**Comment by joaoantoniocardoso** [comment]
> what cameras? how many streams? that is a lot of memory...

This was reported by Tony, using 1x radcam + 1x br cam.

**Comment by maphstr** [comment]
Also experiencing this with two br-cams at rtsp when trying to get webrtc from both. One of them at 1280x720.

**Comment by patrickelectric** [comment]
@joaoantoniocardoso do you know the reason behind this ?

**Comment by joaoantoniocardoso** [comment]
> @joaoantoniocardoso do you know the reason behind this ?

Yes, GStreamer is all dynamic and can request lots of virtual memory

**Comment by patrickelectric** [comment]
But that amount ? What exactly is he allocating and for what ?

**Comment by Williangalvani** [comment]
fixed by #2424
