### ISSUE TITLE
MavP2P fails due to memory limitations

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#2393]
it seems that it allocates a lot of virtual memory, even though it doesnt use pratically anything:

![image](https://github.com/bluerobotics/BlueOS/assets/4013804/3f2583df-b6f5-430d-bbb7-4e25b6a62727)
![image](https://github.com/bluerobotics/BlueOS/assets/4013804/0c6704da-4c38-46c8-b265-da0c9c424775)
[logfile_02-16-2024_18_59_21.log](https://github.com/bluerobotics/BlueOS/files/14315001/logfile_02-16-2024_18_59_21.log)

**Comment by patrickelectric** [comment]
VIRT is 399MB, probably a hard limit of 400MB ?

**Comment by Williangalvani** [comment]
fixed by #2424
