### ISSUE TITLE
bug: Add force remove when deleting local images

### ISSUE THREAD

**Issue by JoaoMario109** [bluerobotics/BlueOS#2431]
### Bug description

Add a force tag when deleting local images in version chooser since some of images are referenced and cannot be deleted

![2024-03-08_09-29](https://github.com/bluerobotics/BlueOS/assets/58235456/d14cfd2b-ad3f-4fab-8650-ebaf72200c2a)

### Steps to reproduce

Try to remove the local version and got this error

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by Williangalvani** [comment]
This happened using dockercompose for development?
bootstrap usually create the containers with --rm so they are removed as soon as they stop, maybe compose can do something similar
