### ISSUE TITLE
bug: Default MAV profile has an unconfigured VeryGenericIndicator

### ISSUE THREAD

**Issue by ArturoManzoli** [bluerobotics/BlueOS#2518]
### Bug description

The default layout for MAV profile has an unconfigured VeryGenericIndicator instance. On cockpit this causes the configuration screen to pop up on profile change/reset.
![image](https://github.com/bluerobotics/BlueOS/assets/14910201/612cdbf4-efd1-47ad-b9cf-c32992b2d998)
****

### Steps to reproduce

 On Cockpit:
* Clear the browser cache with CTRL+Shift+R;
* Press the "Reset profiles to default configuration" button;
* Select the standard profile for MAV;
* The veryGenericIndicator config pops out.

### Primary pain point(s)

On cockpit this causes the configuration screen to pop up on profile change/reset.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by ArturoManzoli** [comment]
I might be wrong, but isn't the original profiles object used on the cockpit fetched from the BlueOS during a layout reset?
If so, the original profile object is stored on the BlueOS and has to be changed there.

**Comment by rafaellehmkuhl** [comment]
@ArturoManzoli they are all in the Cockpit repo. It's on `src/assets/joystick-profiles.ts`.

**Comment by ArturoManzoli** [comment]
The issue was indeed misplaced

**Comment by ArturoManzoli** [comment]
The issue was indeed misplaced
