### ISSUE TITLE
Wrong order in the extensions version menu list

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#2583]
![image](https://github.com/bluerobotics/BlueOS/assets/5920286/33dde07e-882a-48a5-84bc-1716bb132080)

**Comment by patrickelectric** [comment]
@JoaoMario109 we should fix this before moving from -dev manifest

**Comment by JoaoMario109** [comment]
> @JoaoMario109 we should fix this before moving from -dev manifest

Yes, I'll add a version sort for versions in the frontend
