### ISSUE TITLE
bug: BACKEND_OFFLINE

### ISSUE THREAD

**Issue by herwig-** [bluerobotics/BlueOS#2673]
### Bug description

![grafik](https://github.com/bluerobotics/BlueOS/assets/741471/85d17611-3b95-4d43-8e83-b4d756ca276f)

BlueOS Version: heads/master-0-g32243cc2 Build: 6/7/2024, 2:51:13 PM

please note, also internet connection fails...

![grafik](https://github.com/bluerobotics/BlueOS/assets/741471/e8d767b6-6ec4-4526-a922-8b9e4507b708)

is the problem maybe related to the image above? In this image it seams that the repository blueos-core is used instead of the BlueOS ?

### Steps to reproduce

Hardware: rpi3, 4gb model B+
OS: light 64bit

sudo bash
apt update

sudo su -c 'curl -fsSL https://raw.githubusercontent.com/bluerobotics/blueos-docker/master/install/install.sh | bash'

rebooot -> then the bootstrap docker Image keeos running but the core:factory docker image always reboots

![grafik](https://github.com/bluerobotics/BlueOS/assets/741471/2328b8ab-cd07-41bc-af96-6a9703de1c2c)

compare uptime of the two images, the core restarts all 3 to 4 seconds

### Primary pain point(s)

The software does not start as planned

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by joaoantoniocardoso** [comment]
Hi, 64-bit Arm Linux support is still underway. Can you use the old 32-bit version?

> is the problem maybe related to the image above? In this image it seams that the repository blueos-core is used instead of the BlueOS ?

`blueos-core` is correct.

**Comment by herwig-** [comment]
thx, will try the 32-bit version asap

**Comment by herwig-** [comment]
thx, the 32 bit Legacy version worked (after some tries) -> could anybody add a note on the current state of adaption for the available RPi OS versions?
I know that it is impossible to test all systems but it would be good for a newcommer to see which configuration is activley tested and will likely be the best place to start ...
