### ISSUE TITLE
[Wizard] parameters table showing "Unknown" values

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#2702]
![image](https://github.com/bluerobotics/BlueOS/assets/5920286/0a1c7581-d36a-49ad-88ae-3f1fc1952939)

BlueOS Version: tags/1.3.0-beta.5-0-geb70c041

**Comment by patrickelectric** [comment]
That's really weird!

**Comment by JoaoMario109** [comment]
I wasn't able to replicate this, do you have any more info about how to reproduce?

**Comment by patrickelectric** [comment]
I saw that once, it appears to be somehow hard to replicate.

**Comment by joaoantoniocardoso** [comment]
I have the impression that I got disconnected from the internet just before seeing that

**Comment by joaoantoniocardoso** [comment]
update: I just got it again, but only for some parameters. Stable connection this time:

![image](https://github.com/bluerobotics/BlueOS/assets/5920286/affdca0a-2295-40d5-a052-901de2da7270)

**Comment by joaoantoniocardoso** [comment]
It writes the correct parameters. Are we somehow loading the values to the interface before they are gathered (race condition)?
