### ISSUE TITLE
[Autopilot Paramters] user can scroll down beyond items

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#2704]
https://github.com/bluerobotics/BlueOS/assets/5920286/ab26c6f8-dc41-4b26-b6ab-f7fa5599897d

BlueOS Version: tags/1.3.0-beta.5-0-geb70c041

**Comment by patrickelectric** [comment]
Unable to replicate with latest master

![Peek 2024-06-19 14-49](https://github.com/bluerobotics/BlueOS/assets/1215497/7849548a-359b-424c-b1a4-45f163c569eb)

**Comment by joaoantoniocardoso** [comment]
I just updated and tested again (Crhome Version 126.0.6478.61 (Official Build) (64-bit)):

https://github.com/bluerobotics/BlueOS/assets/5920286/97a04606-bbbf-4966-83aa-109e7340e441

**Comment by joaoantoniocardoso** [comment]
My params file:

[Submarine-4.1.2-STABLE-20240521-202146.params.zip](https://github.com/user-attachments/files/15904569/Submarine-4.1.2-STABLE-20240521-202146.params.zip)

**Comment by joaoantoniocardoso** [comment]
Can anyone else check if it happens on other systems? @Williangalvani @rafaellehmkuhl @JoaoMario109

**Comment by patrickelectric** [comment]
@JoaoMario109 was able to replicate and it's investigating it
