### ISSUE TITLE
We should have a guide on how to forward topside internet to the vehicle via tether

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#2716]
[This](https://github.com/bluerobotics/BlueOS/issues/1446#issuecomment-1421515980) might help.

**Comment by ES-Alexander** [comment]
@joaoantoniocardoso is there something missing from [the existing docs](https://blueos.cloud/docs/blueos/1.2/getting-started/#tether-passthrough)?

**Comment by ES-Alexander** [comment]
Closing, since it's a duplicate of #1444, and is already done. You can re-open if there's something missing, although given this is a documentation issue it makes more sense to open in the docs repo 🤷‍♂️

**Comment by joaoantoniocardoso** [comment]
@ES-Alexander I clearly forgotten about it, thanks!
