### ISSUE TITLE
core: frontend: GPS icon is confusing

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS#2721]
### Current behaviour

There's a crosshair with a number on it, which has no intuitive meaning (e.g. are there 5 locations??)

### Expected or desired behaviour

Use a satellite icon (e.g. [mdi-satellite-variant](https://pictogrammers.com/library/mdi/icon/satellite-variant/)), at least when showing the number of connected satellites.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
> ### Current behaviour
> There's a crosshair with a number on it, which has no intuitive meaning (e.g. are there 5 locations??)
> 
> ### Expected or desired behaviour
> Use a satellite icon (e.g. [mdi-satellite-variant](https://pictogrammers.com/library/mdi/icon/satellite-variant/)), at least when showing the number of connected satellites.
> 
> ### Prerequisites
> * [x]  I have checked to make sure that a similar request has not already been filed or fixed.

This to me is more satellite communication than number of satellites. We can add in the tooltip what the number means. The cross + circle icon is a common GPS position indicator for android.

**Comment by patrickelectric** [comment]
This was fixed by #2746
