### ISSUE TITLE
Add better support to blueos RTSP options (TCP/UDP) and etc

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#2737]

**Comment by joaoantoniocardoso** [comment]
Just quoting from the [PR that added it](https://github.com/mavlink/mavlink-camera-manager/pull/391) on MCM side:

> Tested and working with both `rtspsrc` and ffplay:
> 
>     * [x]  `rtsp://` -> both UDP and TCP
> 
>     * [x]  `rtspu://` -> UDP
> 
>     * [x]  `rtspt://` -> TCP
> 
>     * [x]  `rtsph://` -> TCP tunneled via HTTP
> 
>     * [x]  `rtspth://` -> TCP w/ TLS
> 
>     * [x]  `rtspuh://` -> UDP w/ TLS
> 
>     * [x]  `rtspsh://` -> TCP tunneled via HTTP w/ TSL
> 
> 
> Note: a drawback of this approach is that despite the scheme used in the endpoint, the RTSP client would always use `rtsp://` instead.

**Comment by joaoantoniocardoso** [comment]
Maybe we keep showing it to the user as `rtsp://<IP>:<PORT>/<PATH>`, but we add an additional dropdown that has the options as human-readable descriptions.
