### ISSUE TITLE
DepthIndicator filter introduces too much delay

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS#2738]
to the point I thought something was wrong in ardusub...

the filter is here:
https://github.com/bluerobotics/cockpit/blob/master/src/components/mini-widgets/DepthIndicator.vue#L31

**Comment by rafaellehmkuhl** [comment]
This issue should be on Cockpit, right?

**Comment by Williangalvani** [comment]
> This issue should be on Cockpit, right?

https://github.com/bluerobotics/BlueOS/assets/4013804/02f299c5-dfca-4c35-ade3-8e810fe01c2c
