### ISSUE TITLE
Terminal service is listed as unknown

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#2744]
<img width="1187" alt="image" src="https://github.com/bluerobotics/BlueOS/assets/6551040/6d9bcbc6-7484-4fb3-bc4c-26bd88484b47">

**Comment by rafaellehmkuhl** [comment]
Helper logs:

[helper-20240625-171027.gz](https://github.com/user-attachments/files/15975622/helper-20240625-171027.gz)
[logfile_06-25-2024_16:09:37.log](https://github.com/user-attachments/files/15975623/logfile_06-25-2024_16.09.37.log)

**Comment by patrickelectric** [comment]
Do you have the log of bag of holding ?
