### ISSUE TITLE
bug: EKF needle color in new compass widget does not match color key

### ISSUE THREAD

**Issue by clydemcqueen** [bluerobotics/BlueOS#2757]
### Bug description

Testing 1.3.0-beta.6

The new compass widget is nifty! However, the color key seems to be wrong: the EKF needle is black, not cyan. 
![image](https://github.com/bluerobotics/BlueOS/assets/4961326/c101ec8d-29c6-448b-ad7c-dc6d3639bd2c)

### Steps to reproduce

1. blueos.local/vehicle/setup
2. click on configure
3. click on setup

### Primary pain point(s)

User confusion

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
More than that, the colors are not being computed correctly with 3 compasses

![image](https://github.com/bluerobotics/BlueOS/assets/1215497/a52be040-e61b-4592-a7fc-9ad41577ae87)
