### ISSUE TITLE
bug: Is there a build guide available on how to get a raspberry pi image?

### ISSUE THREAD

**Issue by mindfulme** [bluerobotics/BlueOS#2859]
### Bug description

I can't find any dev guide on how to build a raspberry pi 4 image to flash on sd card

### Steps to reproduce

1. Clone repository
2. Follow readme
3. Fail to build

### Primary pain point(s)

Cant build image 

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
Hi @mindfulme, did you run the install script ?

**Comment by mindfulme** [comment]
no, what to do after I run install script?

**Comment by patrickelectric** [comment]
Take a look in https://github.com/bluerobotics/BlueOS#quick-links-, and check the instructions for manual installation.

Is there a reason for not using the provided image ?

**Comment by mindfulme** [comment]
Yes, there is. I need to change an address in `Detector.py` file and rebuild the whole code

**Comment by mindfulme** [comment]
Chech this thread https://discuss.bluerobotics.com/t/blueos-arduplane-4-5-4-firmware-no-sensors-detected-barometer-not-found/17488/13

**Comment by patrickelectric** [comment]
For that, you should be able to modify blueos and build it, after that is done, you should use the version chooser to change the running BlueOS version. 
Check: https://blueos.cloud/docs/blueos/1.1/advanced-usage/#blueos-version

To build you can use buildx with docker or github actions, just a matter to configure your github env variables. 

`DOCKER_USERNAME` and `DOCKER_PASSWORD`.

**Comment by Vils0n** [comment]
built with docker completes just fine, only issue is the constant `pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed` when `Inspect image` runs

**Comment by Vils0n** [comment]
<img width="1417" alt="Снимок экрана 2024-08-15 в 13 04 32" src="https://github.com/user-attachments/assets/349ab394-9941-4801-98b2-6f7789b1e924">

**Comment by Vils0n** [comment]
and build is generated on docker hub, I am able to download it 
<img width="1425" alt="Снимок экрана 2024-08-15 в 13 05 16" src="https://github.com/user-attachments/assets/8862f014-af0a-48c7-9bd5-10831df37767">

**Comment by Vils0n** [comment]
<img width="1244" alt="Снимок экрана 2024-08-15 в 13 15 20" src="https://github.com/user-attachments/assets/216de2b6-d3ea-45ce-b4d1-24585e0432d7">
but where to get `blueos-raspberry.zip` as on screenshot in your official releases

**Comment by Vils0n** [comment]
<img width="913" alt="Снимок экрана 2024-08-15 в 13 22 52" src="https://github.com/user-attachments/assets/3ec7d227-314e-4c10-952c-4d746bcd7410">
I guess this is the easiest way to go, to just upload `.tar` file here from docker hub

**Comment by mindfulme** [comment]
![image](https://github.com/user-attachments/assets/f6bc6cc4-b24b-4d0f-8a15-62496d9e1c58)

@patrickelectric  do you know why it skipped `deploy-raspberry-image` job???

**Comment by mindfulme** [comment]
ok, I resolved everything. Had to change the username here in config file
![image](https://github.com/user-attachments/assets/1fb4c9a5-9aa9-42a7-a6dd-548cc0230c73)

**Comment by patrickelectric** [comment]
Hi @mindfulme I'm glad that you figured it out. Sorry for the late reply, I was in a work trip.
About the raspberry image deployment, you need to setup a self-hosted github action in a raspberry pi to have it running.
To install your custom docker images, you just need to go in pirate mode and put your dockerhub repository name: <user>/<docker>
