### ISSUE TITLE
Question: How do I make a GitHub actions runner environment to use an existing workflow file?

### ISSUE THREAD

**Issue by mindfulme** [bluerobotics/BlueOS#2898]
### Question description
I know how to set up github actions using custom runners (ubuntu lts only). but how does it work with raspberry runner?
`   runs-on: raspbian-armv7-kernel-5.10.33` where do I get it or how to set it up?

` runs-on: blueos-ci`

### Steps to reproduce

Check https://github.com/bluerobotics/BlueOS/blob/d31163bba177495c25ab7d2928418e531d970ed5/.github/workflows/test-and-deploy.yml#L252

and here https://github.com/bluerobotics/navigator-rs/blob/311fdb2eea6a319ed6348a7edbfd349d30068f9e/.github/workflows/action.yml#L61

**Comment by mindfulme** [comment]
like this or some other way? https://github.com/wbond/pi-github-runner

**Comment by patrickelectric** [comment]
It's just necessary to follow the documentation: https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/adding-self-hosted-runners
