### ISSUE TITLE
adding CONTRIBUTING.md and COC.md file

### ISSUE THREAD

**Issue by slayer321** [bluerobotics/BlueOS#297]
I will like to take this issue

**Comment by rafaellehmkuhl** [comment]
Sure! Could you bring some examples to discuss?

**Comment by slayer321** [comment]
I think these two looks good [CONTRIBUTING.md](https://github.com/Vyvy-vi/TEC-Discord-Oauth2/blob/main/CONTRIBUTING.md) 
 and [COC.md](https://github.com/Vyvy-vi/TEC-Discord-Oauth2/blob/main/CODE_OF_CONDUCT.md) . Though I was the one who added this file to that repo.

**Comment by rafaellehmkuhl** [comment]
@patrickelectric what do you think?
