### ISSUE TITLE
build: yarn install & build is taking too much time

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#437]
Yarn is taking a long time (10 minutes on Rasp4) to run install and build commands (`3/27 : RUN cd /home/pi/frontend && yarn install --network-timeout=300000 && yarn build --skip-plugins @vue/cli-plugin-eslint`).

It would be good to take a look at that and see what's going on. On my machine (i7 3gen) it takes at least than times less for both operations.

DAYS_TO_DEVELOP:3

**Comment by Williangalvani** [comment]
Maybe we can separate the Build and Test steps in CI

**Comment by rafaellehmkuhl** [comment]
The timeout on package fetch, which stales, is the result of a bug on yarn that [was fixed only for v2 onwards](https://github.com/yarnpkg/yarn/issues/8242).

To migrate to yarn v2 we should follow [this guide](https://yarnpkg.com/getting-started/migration).

**Comment by patrickelectric** [comment]
Fixed by bun
