### ISSUE TITLE
ardupilot-manager: Allow users to choose toggle between MavlinkRouter and MavProxy

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#481]
We clearly have a problem with mavlink routers. MavProxy works but is *very* resource-consuming, while MavlinkRouter (our current default, and only one available on install) has several problems (from not supporting tlogs to suddenly dying on endpoint creation).

While we don't have definitive solutions for that, we could allow users to toggle between both.

This would demand:
1. Including MavProxy on companion installation
2. Adding API for toggling between both
3. Adding button to frontend

**Comment by patrickelectric** [comment]
Fixed by https://github.com/bluerobotics/BlueOS/pull/2072 https://github.com/bluerobotics/BlueOS/pull/2235
