### ISSUE TITLE
frontend: Remove old frontends

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#532]
As we assume the new integrated frontends are already stable, or at least more evolved than the old ones, we should remove the later so users don't get confused and we have less code to maintain.

DAYS_TO_DEVELOP:0.3

**Comment by rafaellehmkuhl** [comment]
I mean for the other services, that we are not using the old frontends anymore (wifi, cable-guy, ardupilot-manager, etc).

Version-chooser seems to be the only one we need to keep while not moved.

**Comment by patrickelectric** [comment]
Should be fixed by now
