### ISSUE TITLE
camera-manager: Two camera devices appearing for same USB camera

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS#548]
First one have plenty of controls and H264 encoding available.
Second one has no controls and MJPG+YUYV encondings available.
They also appear to come from different sources (video0 vs video2).

![image](https://user-images.githubusercontent.com/6551040/137013083-f4788fe1-153e-4de5-bce0-759a1cbe60c9.png)

@patrickelectric is this the expected behavior.

**Comment by patrickelectric** [comment]
Yes, this is the expected behaviour, linux driver provides two different video devices from the same camera.

**Comment by patrickelectric** [comment]
For now.. it's a good thing to do until we finish the backend.
