### ISSUE TITLE
bug: Logs page creates an error notification if there is no /logs folder

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS#957]
### Bug description

![image](https://user-images.githubusercontent.com/1215497/161978325-c34e550e-1512-4130-a4a5-a041924f0d55.png)

### Steps to reproduce

Fresh install BlueOS
Go to logs

### Primary pain point(s)

The error message should be removed and we should only say that there are no logs.
We could also create the logs folder by default in the backend. 

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
We now have the folder

**Comment by joaoantoniocardoso** [comment]
closed by #2044
