### ISSUE TITLE
Menu text/icons are blurred on chrome.

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS#970]
### Current behaviour

On Chrome/Edge, menu fonts and icons are rendering a little blurred, getting sharper when the mouse enters and leaves the menu. It looks always sharp on Firefox.

https://user-images.githubusercontent.com/5920286/162448671-3f6df029-05ea-42f7-a6cd-12f955ca555d.mp4

### Expected or desired behaviour

Icons and texts to be always sharp.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
It's fine here:

<img width="354" alt="image" src="https://user-images.githubusercontent.com/6551040/162459833-ee47d096-9456-4532-9ad9-2880f5ae1783.png">

Version 100.0.4896.75 (Official Build) (arm64)
MacOS Monterey 12.2.1

Edge is also fine.

**Comment by rafaellehmkuhl** [comment]
Apparently this is a bug with the chromium engine. I just updated Edge to `99.0.1150.36` and I'm now seeing the same issue.

**Comment by patrickelectric** [comment]
@joaoantoniocardoso let us know if this is a thing

**Comment by joaoantoniocardoso** [comment]
Looks all good:
![image](https://github.com/bluerobotics/BlueOS/assets/5920286/9094bace-9230-4aad-a67c-fea1343b2196)

Firefox (left), Chrome (right)
